//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/slyons/repos/P/Src/PCompiler/CompilerCore/Parser/PParser.g4 by ANTLR 4.6.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Plang.Compiler {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class PParserBaseListener : IPParserListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>AssertModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssertModuleExpr([NotNull] PParser.AssertModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssertModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssertModuleExpr([NotNull] PParser.AssertModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>HideInterfacesModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHideInterfacesModuleExpr([NotNull] PParser.HideInterfacesModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HideInterfacesModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHideInterfacesModuleExpr([NotNull] PParser.HideInterfacesModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ParenModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenModuleExpr([NotNull] PParser.ParenModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenModuleExpr([NotNull] PParser.ParenModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>RenameModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRenameModuleExpr([NotNull] PParser.RenameModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RenameModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRenameModuleExpr([NotNull] PParser.RenameModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedModule</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedModule([NotNull] PParser.NamedModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedModule</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedModule([NotNull] PParser.NamedModuleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveModuleExpr([NotNull] PParser.PrimitiveModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveModuleExpr([NotNull] PParser.PrimitiveModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>UnionModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionModuleExpr([NotNull] PParser.UnionModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnionModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionModuleExpr([NotNull] PParser.UnionModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>HideEventsModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHideEventsModuleExpr([NotNull] PParser.HideEventsModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HideEventsModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHideEventsModuleExpr([NotNull] PParser.HideEventsModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ComposeModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComposeModuleExpr([NotNull] PParser.ComposeModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ComposeModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComposeModuleExpr([NotNull] PParser.ComposeModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>MainMachineModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainMachineModuleExpr([NotNull] PParser.MainMachineModuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MainMachineModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainMachineModuleExpr([NotNull] PParser.MainMachineModuleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>SetType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetType([NotNull] PParser.SetTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SetType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetType([NotNull] PParser.SetTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>SeqType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeqType([NotNull] PParser.SeqTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SeqType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeqType([NotNull] PParser.SeqTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedType([NotNull] PParser.NamedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedType([NotNull] PParser.NamedTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>TupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleType([NotNull] PParser.TupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleType([NotNull] PParser.TupleTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedTupleType([NotNull] PParser.NamedTupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedTupleType([NotNull] PParser.NamedTupleTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] PParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] PParser.PrimitiveTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapType([NotNull] PParser.MapTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapType([NotNull] PParser.MapTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ExpFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpFloat([NotNull] PParser.ExpFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpFloat([NotNull] PParser.ExpFloatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalFloat([NotNull] PParser.DecimalFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalFloat([NotNull] PParser.DecimalFloatContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>StateEntry</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateEntry([NotNull] PParser.StateEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StateEntry</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateEntry([NotNull] PParser.StateEntryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>OnEventDoAction</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnEventDoAction([NotNull] PParser.OnEventDoActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OnEventDoAction</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnEventDoAction([NotNull] PParser.OnEventDoActionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>StateExit</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateExit([NotNull] PParser.StateExitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StateExit</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateExit([NotNull] PParser.StateExitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>OnEventGotoState</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnEventGotoState([NotNull] PParser.OnEventGotoStateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OnEventGotoState</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnEventGotoState([NotNull] PParser.OnEventGotoStateContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>StateIgnore</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateIgnore([NotNull] PParser.StateIgnoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StateIgnore</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateIgnore([NotNull] PParser.StateIgnoreContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>StateDefer</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDefer([NotNull] PParser.StateDeferContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StateDefer</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDefer([NotNull] PParser.StateDeferContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>SafetyTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSafetyTestDecl([NotNull] PParser.SafetyTestDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SafetyTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSafetyTestDecl([NotNull] PParser.SafetyTestDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>RefinementTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefinementTestDecl([NotNull] PParser.RefinementTestDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RefinementTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefinementTestDecl([NotNull] PParser.RefinementTestDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ProveUsingCmd</c>
	/// labeled alternative in <see cref="PParser.proofItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProveUsingCmd([NotNull] PParser.ProveUsingCmdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ProveUsingCmd</c>
	/// labeled alternative in <see cref="PParser.proofItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProveUsingCmd([NotNull] PParser.ProveUsingCmdContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ProofBlock</c>
	/// labeled alternative in <see cref="PParser.proofBlockDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProofBlock([NotNull] PParser.ProofBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ProofBlock</c>
	/// labeled alternative in <see cref="PParser.proofBlockDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProofBlock([NotNull] PParser.ProofBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>MachineReceive</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineReceive([NotNull] PParser.MachineReceiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MachineReceive</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineReceive([NotNull] PParser.MachineReceiveContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>MachineSend</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineSend([NotNull] PParser.MachineSendContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MachineSend</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineSend([NotNull] PParser.MachineSendContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ForeignFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeignFunDecl([NotNull] PParser.ForeignFunDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForeignFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeignFunDecl([NotNull] PParser.ForeignFunDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>PFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPFunDecl([NotNull] PParser.PFunDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPFunDecl([NotNull] PParser.PFunDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>RemoveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoveStmt([NotNull] PParser.RemoveStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RemoveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoveStmt([NotNull] PParser.RemoveStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ReceiveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReceiveStmt([NotNull] PParser.ReceiveStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReceiveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReceiveStmt([NotNull] PParser.ReceiveStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintStmt([NotNull] PParser.PrintStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintStmt([NotNull] PParser.PrintStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>SendStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSendStmt([NotNull] PParser.SendStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SendStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSendStmt([NotNull] PParser.SendStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>CompoundStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundStmt([NotNull] PParser.CompoundStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CompoundStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundStmt([NotNull] PParser.CompoundStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>CtorStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtorStmt([NotNull] PParser.CtorStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CtorStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtorStmt([NotNull] PParser.CtorStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>AssignStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmt([NotNull] PParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmt([NotNull] PParser.AssignStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>InsertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsertStmt([NotNull] PParser.InsertStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InsertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsertStmt([NotNull] PParser.InsertStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>AnnounceStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnounceStmt([NotNull] PParser.AnnounceStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AnnounceStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnounceStmt([NotNull] PParser.AnnounceStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>AddStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddStmt([NotNull] PParser.AddStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddStmt([NotNull] PParser.AddStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>RaiseStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaiseStmt([NotNull] PParser.RaiseStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RaiseStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaiseStmt([NotNull] PParser.RaiseStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ForeachStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachStmt([NotNull] PParser.ForeachStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForeachStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachStmt([NotNull] PParser.ForeachStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>AssumeStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssumeStmt([NotNull] PParser.AssumeStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssumeStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssumeStmt([NotNull] PParser.AssumeStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStmt([NotNull] PParser.ContinueStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStmt([NotNull] PParser.ContinueStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] PParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] PParser.IfStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>FunCallStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunCallStmt([NotNull] PParser.FunCallStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FunCallStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunCallStmt([NotNull] PParser.FunCallStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoStmt([NotNull] PParser.NoStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoStmt([NotNull] PParser.NoStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] PParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] PParser.WhileStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStmt([NotNull] PParser.BreakStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStmt([NotNull] PParser.BreakStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>GotoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoStmt([NotNull] PParser.GotoStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GotoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoStmt([NotNull] PParser.GotoStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>AssertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssertStmt([NotNull] PParser.AssertStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssertStmt([NotNull] PParser.AssertStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] PParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] PParser.ReturnStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>StringExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringExpr([NotNull] PParser.StringExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringExpr([NotNull] PParser.StringExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>SentExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentExpr([NotNull] PParser.SentExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SentExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentExpr([NotNull] PParser.SentExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>KeywordExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeywordExpr([NotNull] PParser.KeywordExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>KeywordExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeywordExpr([NotNull] PParser.KeywordExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>SeqAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeqAccessExpr([NotNull] PParser.SeqAccessExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SeqAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeqAccessExpr([NotNull] PParser.SeqAccessExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ChooseExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChooseExpr([NotNull] PParser.ChooseExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ChooseExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChooseExpr([NotNull] PParser.ChooseExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedTupleAccessExpr([NotNull] PParser.NamedTupleAccessExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedTupleAccessExpr([NotNull] PParser.NamedTupleAccessExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveExpr([NotNull] PParser.PrimitiveExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveExpr([NotNull] PParser.PrimitiveExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>BinExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinExpr([NotNull] PParser.BinExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinExpr([NotNull] PParser.BinExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] PParser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] PParser.UnaryExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>TupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleAccessExpr([NotNull] PParser.TupleAccessExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleAccessExpr([NotNull] PParser.TupleAccessExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>FlyingExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlyingExpr([NotNull] PParser.FlyingExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FlyingExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlyingExpr([NotNull] PParser.FlyingExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>UnnamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnnamedTupleExpr([NotNull] PParser.UnnamedTupleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnnamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnnamedTupleExpr([NotNull] PParser.UnnamedTupleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>FunCallExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunCallExpr([NotNull] PParser.FunCallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FunCallExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunCallExpr([NotNull] PParser.FunCallExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpr([NotNull] PParser.CastExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpr([NotNull] PParser.CastExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>TargetsExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTargetsExpr([NotNull] PParser.TargetsExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TargetsExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTargetsExpr([NotNull] PParser.TargetsExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>CtorExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtorExpr([NotNull] PParser.CtorExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CtorExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtorExpr([NotNull] PParser.CtorExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] PParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] PParser.ParenExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>QuantExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantExpr([NotNull] PParser.QuantExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>QuantExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantExpr([NotNull] PParser.QuantExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedTupleExpr([NotNull] PParser.NamedTupleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedTupleExpr([NotNull] PParser.NamedTupleExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>TestExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestExpr([NotNull] PParser.TestExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TestExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestExpr([NotNull] PParser.TestExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ForeignTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeignTypeDef([NotNull] PParser.ForeignTypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ForeignTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeignTypeDef([NotNull] PParser.ForeignTypeDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>PTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPTypeDef([NotNull] PParser.PTypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPTypeDef([NotNull] PParser.PTypeDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>TupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleLvalue([NotNull] PParser.TupleLvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleLvalue([NotNull] PParser.TupleLvalueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedTupleLvalue([NotNull] PParser.NamedTupleLvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedTupleLvalue([NotNull] PParser.NamedTupleLvalueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>MapOrSeqLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapOrSeqLvalue([NotNull] PParser.MapOrSeqLvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MapOrSeqLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapOrSeqLvalue([NotNull] PParser.MapOrSeqLvalueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>VarLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarLvalue([NotNull] PParser.VarLvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarLvalue([NotNull] PParser.VarLvalueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] PParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] PParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.iden"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIden([NotNull] PParser.IdenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.iden"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIden([NotNull] PParser.IdenContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] PParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] PParser.IntContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] PParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] PParser.TypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.idenTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdenTypeList([NotNull] PParser.IdenTypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.idenTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdenTypeList([NotNull] PParser.IdenTypeListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.idenType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdenType([NotNull] PParser.IdenTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.idenType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdenType([NotNull] PParser.IdenTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.funParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunParamList([NotNull] PParser.FunParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.funParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunParamList([NotNull] PParser.FunParamListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.funParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunParam([NotNull] PParser.FunParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.funParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunParam([NotNull] PParser.FunParamContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.topDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopDecl([NotNull] PParser.TopDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.topDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopDecl([NotNull] PParser.TopDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.invariantGroupDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvariantGroupDecl([NotNull] PParser.InvariantGroupDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.invariantGroupDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvariantGroupDecl([NotNull] PParser.InvariantGroupDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.proofBlockDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProofBlockDecl([NotNull] PParser.ProofBlockDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.proofBlockDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProofBlockDecl([NotNull] PParser.ProofBlockDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.proofBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProofBody([NotNull] PParser.ProofBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.proofBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProofBody([NotNull] PParser.ProofBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.proofItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProofItem([NotNull] PParser.ProofItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.proofItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProofItem([NotNull] PParser.ProofItemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.globalParamDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalParamDecl([NotNull] PParser.GlobalParamDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.globalParamDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalParamDecl([NotNull] PParser.GlobalParamDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.typeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDefDecl([NotNull] PParser.TypeDefDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.typeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDefDecl([NotNull] PParser.TypeDefDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.enumTypeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumTypeDefDecl([NotNull] PParser.EnumTypeDefDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.enumTypeDefDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumTypeDefDecl([NotNull] PParser.EnumTypeDefDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.enumElemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumElemList([NotNull] PParser.EnumElemListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.enumElemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumElemList([NotNull] PParser.EnumElemListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.enumElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumElem([NotNull] PParser.EnumElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.enumElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumElem([NotNull] PParser.EnumElemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.numberedEnumElemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberedEnumElemList([NotNull] PParser.NumberedEnumElemListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.numberedEnumElemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberedEnumElemList([NotNull] PParser.NumberedEnumElemListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.numberedEnumElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberedEnumElem([NotNull] PParser.NumberedEnumElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.numberedEnumElem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberedEnumElem([NotNull] PParser.NumberedEnumElemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventDecl([NotNull] PParser.EventDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventDecl([NotNull] PParser.EventDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventSetDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventSetDecl([NotNull] PParser.EventSetDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventSetDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventSetDecl([NotNull] PParser.EventSetDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventSetLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventSetLiteral([NotNull] PParser.EventSetLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventSetLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventSetLiteral([NotNull] PParser.EventSetLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.interfaceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDecl([NotNull] PParser.InterfaceDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.interfaceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDecl([NotNull] PParser.InterfaceDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.implMachineDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplMachineDecl([NotNull] PParser.ImplMachineDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.implMachineDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplMachineDecl([NotNull] PParser.ImplMachineDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.idenList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdenList([NotNull] PParser.IdenListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.idenList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdenList([NotNull] PParser.IdenListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.receivesSends"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReceivesSends([NotNull] PParser.ReceivesSendsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.receivesSends"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReceivesSends([NotNull] PParser.ReceivesSendsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.specMachineDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecMachineDecl([NotNull] PParser.SpecMachineDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.specMachineDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecMachineDecl([NotNull] PParser.SpecMachineDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.machineBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineBody([NotNull] PParser.MachineBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.machineBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineBody([NotNull] PParser.MachineBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.machineEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachineEntry([NotNull] PParser.MachineEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.machineEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachineEntry([NotNull] PParser.MachineEntryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] PParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] PParser.VarDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunDecl([NotNull] PParser.FunDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.funDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunDecl([NotNull] PParser.FunDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.pureDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPureDecl([NotNull] PParser.PureDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.pureDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPureDecl([NotNull] PParser.PureDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.invariantDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvariantDecl([NotNull] PParser.InvariantDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.invariantDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvariantDecl([NotNull] PParser.InvariantDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.axiomDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxiomDecl([NotNull] PParser.AxiomDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.axiomDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxiomDecl([NotNull] PParser.AxiomDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.assumeOnStartDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssumeOnStartDecl([NotNull] PParser.AssumeOnStartDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.assumeOnStartDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssumeOnStartDecl([NotNull] PParser.AssumeOnStartDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.stateDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDecl([NotNull] PParser.StateDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.stateDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDecl([NotNull] PParser.StateDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateBodyItem([NotNull] PParser.StateBodyItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.stateBodyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateBodyItem([NotNull] PParser.StateBodyItemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.nonDefaultEventList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonDefaultEventList([NotNull] PParser.NonDefaultEventListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.nonDefaultEventList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonDefaultEventList([NotNull] PParser.NonDefaultEventListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.nonDefaultEvent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonDefaultEvent([NotNull] PParser.NonDefaultEventContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.nonDefaultEvent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonDefaultEvent([NotNull] PParser.NonDefaultEventContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventList([NotNull] PParser.EventListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventList([NotNull] PParser.EventListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventId([NotNull] PParser.EventIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventId([NotNull] PParser.EventIdContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.stateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateName([NotNull] PParser.StateNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.stateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateName([NotNull] PParser.StateNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionBody([NotNull] PParser.FunctionBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionBody([NotNull] PParser.FunctionBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLvalue([NotNull] PParser.LvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLvalue([NotNull] PParser.LvalueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.recvCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecvCase([NotNull] PParser.RecvCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.recvCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecvCase([NotNull] PParser.RecvCaseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.anonEventHandler"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnonEventHandler([NotNull] PParser.AnonEventHandlerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.anonEventHandler"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnonEventHandler([NotNull] PParser.AnonEventHandlerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.noParamAnonEventHandler"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoParamAnonEventHandler([NotNull] PParser.NoParamAnonEventHandlerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.noParamAnonEventHandler"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoParamAnonEventHandler([NotNull] PParser.NoParamAnonEventHandlerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] PParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] PParser.ExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.formatedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormatedString([NotNull] PParser.FormatedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.formatedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormatedString([NotNull] PParser.FormatedStringContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive([NotNull] PParser.PrimitiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive([NotNull] PParser.PrimitiveContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] PParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] PParser.FloatLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.unnamedTupleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnnamedTupleBody([NotNull] PParser.UnnamedTupleBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.unnamedTupleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnnamedTupleBody([NotNull] PParser.UnnamedTupleBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.namedTupleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedTupleBody([NotNull] PParser.NamedTupleBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.namedTupleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedTupleBody([NotNull] PParser.NamedTupleBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.rvalueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRvalueList([NotNull] PParser.RvalueListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.rvalueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRvalueList([NotNull] PParser.RvalueListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.rvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRvalue([NotNull] PParser.RvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.rvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRvalue([NotNull] PParser.RvalueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModExpr([NotNull] PParser.ModExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.modExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModExpr([NotNull] PParser.ModExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.bindExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindExpr([NotNull] PParser.BindExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.bindExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindExpr([NotNull] PParser.BindExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.namedModuleDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedModuleDecl([NotNull] PParser.NamedModuleDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.namedModuleDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedModuleDecl([NotNull] PParser.NamedModuleDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.seqPrimitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeqPrimitive([NotNull] PParser.SeqPrimitiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.seqPrimitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeqPrimitive([NotNull] PParser.SeqPrimitiveContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.seqLiteralBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeqLiteralBody([NotNull] PParser.SeqLiteralBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.seqLiteralBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeqLiteralBody([NotNull] PParser.SeqLiteralBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.seqLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeqLiteral([NotNull] PParser.SeqLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.seqLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeqLiteral([NotNull] PParser.SeqLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.paramBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamBody([NotNull] PParser.ParamBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.paramBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamBody([NotNull] PParser.ParamBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] PParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] PParser.ParamContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.twise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTwise([NotNull] PParser.TwiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.twise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTwise([NotNull] PParser.TwiseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.testDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestDecl([NotNull] PParser.TestDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.testDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestDecl([NotNull] PParser.TestDeclContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.implementationDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementationDecl([NotNull] PParser.ImplementationDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.implementationDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementationDecl([NotNull] PParser.ImplementationDeclContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Plang.Compiler
