//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/slyons/repos/P/Src/PCompiler/CompilerCore/Parser/PParser.g4 by ANTLR 4.6.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Plang.Compiler {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IPParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>AssertModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertModuleExpr([NotNull] PParser.AssertModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>HideInterfacesModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHideInterfacesModuleExpr([NotNull] PParser.HideInterfacesModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ParenModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenModuleExpr([NotNull] PParser.ParenModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>RenameModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRenameModuleExpr([NotNull] PParser.RenameModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NamedModule</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedModule([NotNull] PParser.NamedModuleContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>PrimitiveModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveModuleExpr([NotNull] PParser.PrimitiveModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>UnionModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionModuleExpr([NotNull] PParser.UnionModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>HideEventsModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHideEventsModuleExpr([NotNull] PParser.HideEventsModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ComposeModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposeModuleExpr([NotNull] PParser.ComposeModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>MainMachineModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainMachineModuleExpr([NotNull] PParser.MainMachineModuleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SetType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetType([NotNull] PParser.SetTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SeqType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeqType([NotNull] PParser.SeqTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedType([NotNull] PParser.NamedTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>TupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleType([NotNull] PParser.TupleTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NamedTupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedTupleType([NotNull] PParser.NamedTupleTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>PrimitiveType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] PParser.PrimitiveTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapType([NotNull] PParser.MapTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ExpFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpFloat([NotNull] PParser.ExpFloatContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>DecimalFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalFloat([NotNull] PParser.DecimalFloatContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>StateEntry</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateEntry([NotNull] PParser.StateEntryContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>OnEventDoAction</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnEventDoAction([NotNull] PParser.OnEventDoActionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>StateExit</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateExit([NotNull] PParser.StateExitContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>OnEventGotoState</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnEventGotoState([NotNull] PParser.OnEventGotoStateContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>StateIgnore</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateIgnore([NotNull] PParser.StateIgnoreContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>StateDefer</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateDefer([NotNull] PParser.StateDeferContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SafetyTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSafetyTestDecl([NotNull] PParser.SafetyTestDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>RefinementTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefinementTestDecl([NotNull] PParser.RefinementTestDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ProveUsingCmd</c>
	/// labeled alternative in <see cref="PParser.proofItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProveUsingCmd([NotNull] PParser.ProveUsingCmdContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ProofBlock</c>
	/// labeled alternative in <see cref="PParser.proofBlockDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProofBlock([NotNull] PParser.ProofBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>MachineReceive</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineReceive([NotNull] PParser.MachineReceiveContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>MachineSend</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineSend([NotNull] PParser.MachineSendContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ForeignFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeignFunDecl([NotNull] PParser.ForeignFunDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>PFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPFunDecl([NotNull] PParser.PFunDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>RemoveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemoveStmt([NotNull] PParser.RemoveStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ReceiveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceiveStmt([NotNull] PParser.ReceiveStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStmt([NotNull] PParser.PrintStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SendStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSendStmt([NotNull] PParser.SendStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>CompoundStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundStmt([NotNull] PParser.CompoundStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>CtorStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtorStmt([NotNull] PParser.CtorStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStmt([NotNull] PParser.AssignStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>InsertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertStmt([NotNull] PParser.InsertStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>AnnounceStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnounceStmt([NotNull] PParser.AnnounceStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>AddStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddStmt([NotNull] PParser.AddStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>RaiseStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseStmt([NotNull] PParser.RaiseStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ForeachStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStmt([NotNull] PParser.ForeachStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>AssumeStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssumeStmt([NotNull] PParser.AssumeStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStmt([NotNull] PParser.ContinueStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] PParser.IfStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>FunCallStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunCallStmt([NotNull] PParser.FunCallStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoStmt([NotNull] PParser.NoStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] PParser.WhileStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStmt([NotNull] PParser.BreakStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>GotoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStmt([NotNull] PParser.GotoStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>AssertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertStmt([NotNull] PParser.AssertStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] PParser.ReturnStmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>StringExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpr([NotNull] PParser.StringExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SentExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentExpr([NotNull] PParser.SentExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>KeywordExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeywordExpr([NotNull] PParser.KeywordExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>SeqAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeqAccessExpr([NotNull] PParser.SeqAccessExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ChooseExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChooseExpr([NotNull] PParser.ChooseExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NamedTupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedTupleAccessExpr([NotNull] PParser.NamedTupleAccessExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>PrimitiveExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveExpr([NotNull] PParser.PrimitiveExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>BinExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinExpr([NotNull] PParser.BinExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] PParser.UnaryExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>TupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleAccessExpr([NotNull] PParser.TupleAccessExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>FlyingExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlyingExpr([NotNull] PParser.FlyingExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>UnnamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnnamedTupleExpr([NotNull] PParser.UnnamedTupleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>FunCallExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunCallExpr([NotNull] PParser.FunCallExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>CastExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpr([NotNull] PParser.CastExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>TargetsExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTargetsExpr([NotNull] PParser.TargetsExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>CtorExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtorExpr([NotNull] PParser.CtorExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] PParser.ParenExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>QuantExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantExpr([NotNull] PParser.QuantExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedTupleExpr([NotNull] PParser.NamedTupleExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>TestExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTestExpr([NotNull] PParser.TestExprContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ForeignTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeignTypeDef([NotNull] PParser.ForeignTypeDefContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>PTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPTypeDef([NotNull] PParser.PTypeDefContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>TupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleLvalue([NotNull] PParser.TupleLvalueContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>NamedTupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedTupleLvalue([NotNull] PParser.NamedTupleLvalueContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>MapOrSeqLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapOrSeqLvalue([NotNull] PParser.MapOrSeqLvalueContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>VarLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarLvalue([NotNull] PParser.VarLvalueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] PParser.ProgramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.iden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIden([NotNull] PParser.IdenContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] PParser.IntContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] PParser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.idenTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdenTypeList([NotNull] PParser.IdenTypeListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.idenType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdenType([NotNull] PParser.IdenTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.funParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunParamList([NotNull] PParser.FunParamListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.funParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunParam([NotNull] PParser.FunParamContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.topDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopDecl([NotNull] PParser.TopDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.invariantGroupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvariantGroupDecl([NotNull] PParser.InvariantGroupDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.proofBlockDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProofBlockDecl([NotNull] PParser.ProofBlockDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.proofBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProofBody([NotNull] PParser.ProofBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.proofItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProofItem([NotNull] PParser.ProofItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.globalParamDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalParamDecl([NotNull] PParser.GlobalParamDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDefDecl([NotNull] PParser.TypeDefDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.enumTypeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumTypeDefDecl([NotNull] PParser.EnumTypeDefDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.enumElemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumElemList([NotNull] PParser.EnumElemListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.enumElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumElem([NotNull] PParser.EnumElemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.numberedEnumElemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberedEnumElemList([NotNull] PParser.NumberedEnumElemListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.numberedEnumElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberedEnumElem([NotNull] PParser.NumberedEnumElemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventDecl([NotNull] PParser.EventDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.eventSetDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventSetDecl([NotNull] PParser.EventSetDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.eventSetLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventSetLiteral([NotNull] PParser.EventSetLiteralContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDecl([NotNull] PParser.InterfaceDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.implMachineDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplMachineDecl([NotNull] PParser.ImplMachineDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.idenList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdenList([NotNull] PParser.IdenListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceivesSends([NotNull] PParser.ReceivesSendsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.specMachineDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecMachineDecl([NotNull] PParser.SpecMachineDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.machineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineBody([NotNull] PParser.MachineBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.machineEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachineEntry([NotNull] PParser.MachineEntryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] PParser.VarDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunDecl([NotNull] PParser.FunDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.pureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPureDecl([NotNull] PParser.PureDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.invariantDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvariantDecl([NotNull] PParser.InvariantDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.axiomDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxiomDecl([NotNull] PParser.AxiomDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.assumeOnStartDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssumeOnStartDecl([NotNull] PParser.AssumeOnStartDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.stateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateDecl([NotNull] PParser.StateDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateBodyItem([NotNull] PParser.StateBodyItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.nonDefaultEventList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonDefaultEventList([NotNull] PParser.NonDefaultEventListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.nonDefaultEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonDefaultEvent([NotNull] PParser.NonDefaultEventContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.eventList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventList([NotNull] PParser.EventListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.eventId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventId([NotNull] PParser.EventIdContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateName([NotNull] PParser.StateNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBody([NotNull] PParser.FunctionBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] PParser.StatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLvalue([NotNull] PParser.LvalueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.recvCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecvCase([NotNull] PParser.RecvCaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.anonEventHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonEventHandler([NotNull] PParser.AnonEventHandlerContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.noParamAnonEventHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoParamAnonEventHandler([NotNull] PParser.NoParamAnonEventHandlerContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] PParser.ExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.formatedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormatedString([NotNull] PParser.FormatedStringContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.primitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitive([NotNull] PParser.PrimitiveContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] PParser.FloatLiteralContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.unnamedTupleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnnamedTupleBody([NotNull] PParser.UnnamedTupleBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.namedTupleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedTupleBody([NotNull] PParser.NamedTupleBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.rvalueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRvalueList([NotNull] PParser.RvalueListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRvalue([NotNull] PParser.RvalueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModExpr([NotNull] PParser.ModExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.bindExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindExpr([NotNull] PParser.BindExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.namedModuleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedModuleDecl([NotNull] PParser.NamedModuleDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.seqPrimitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeqPrimitive([NotNull] PParser.SeqPrimitiveContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.seqLiteralBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeqLiteralBody([NotNull] PParser.SeqLiteralBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.seqLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeqLiteral([NotNull] PParser.SeqLiteralContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.paramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamBody([NotNull] PParser.ParamBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] PParser.ParamContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.twise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTwise([NotNull] PParser.TwiseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTestDecl([NotNull] PParser.TestDeclContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PParser.implementationDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplementationDecl([NotNull] PParser.ImplementationDeclContext context);
}
} // namespace Plang.Compiler
