//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/slyons/repos/P/Src/PCompiler/CompilerCore/Parser/PParser.g4 by ANTLR 4.6.5-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Plang.Compiler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IPParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>AssertModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertModuleExpr([NotNull] PParser.AssertModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssertModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertModuleExpr([NotNull] PParser.AssertModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>HideInterfacesModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHideInterfacesModuleExpr([NotNull] PParser.HideInterfacesModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>HideInterfacesModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHideInterfacesModuleExpr([NotNull] PParser.HideInterfacesModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ParenModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenModuleExpr([NotNull] PParser.ParenModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenModuleExpr([NotNull] PParser.ParenModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>RenameModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRenameModuleExpr([NotNull] PParser.RenameModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RenameModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRenameModuleExpr([NotNull] PParser.RenameModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedModule</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedModule([NotNull] PParser.NamedModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedModule</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedModule([NotNull] PParser.NamedModuleContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveModuleExpr([NotNull] PParser.PrimitiveModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveModuleExpr([NotNull] PParser.PrimitiveModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>UnionModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionModuleExpr([NotNull] PParser.UnionModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnionModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionModuleExpr([NotNull] PParser.UnionModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>HideEventsModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHideEventsModuleExpr([NotNull] PParser.HideEventsModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>HideEventsModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHideEventsModuleExpr([NotNull] PParser.HideEventsModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ComposeModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComposeModuleExpr([NotNull] PParser.ComposeModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ComposeModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComposeModuleExpr([NotNull] PParser.ComposeModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>MainMachineModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainMachineModuleExpr([NotNull] PParser.MainMachineModuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MainMachineModuleExpr</c>
	/// labeled alternative in <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainMachineModuleExpr([NotNull] PParser.MainMachineModuleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>SetType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetType([NotNull] PParser.SetTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SetType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetType([NotNull] PParser.SetTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>SeqType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeqType([NotNull] PParser.SeqTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SeqType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeqType([NotNull] PParser.SeqTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedType([NotNull] PParser.NamedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedType([NotNull] PParser.NamedTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>TupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleType([NotNull] PParser.TupleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleType([NotNull] PParser.TupleTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedTupleType([NotNull] PParser.NamedTupleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedTupleType([NotNull] PParser.NamedTupleTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] PParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] PParser.PrimitiveTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapType([NotNull] PParser.MapTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapType([NotNull] PParser.MapTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ExpFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpFloat([NotNull] PParser.ExpFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpFloat([NotNull] PParser.ExpFloatContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>DecimalFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimalFloat([NotNull] PParser.DecimalFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DecimalFloat</c>
	/// labeled alternative in <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimalFloat([NotNull] PParser.DecimalFloatContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>StateEntry</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateEntry([NotNull] PParser.StateEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StateEntry</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateEntry([NotNull] PParser.StateEntryContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>OnEventDoAction</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnEventDoAction([NotNull] PParser.OnEventDoActionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OnEventDoAction</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnEventDoAction([NotNull] PParser.OnEventDoActionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>StateExit</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateExit([NotNull] PParser.StateExitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StateExit</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateExit([NotNull] PParser.StateExitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>OnEventGotoState</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnEventGotoState([NotNull] PParser.OnEventGotoStateContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OnEventGotoState</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnEventGotoState([NotNull] PParser.OnEventGotoStateContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>StateIgnore</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateIgnore([NotNull] PParser.StateIgnoreContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StateIgnore</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateIgnore([NotNull] PParser.StateIgnoreContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>StateDefer</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateDefer([NotNull] PParser.StateDeferContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StateDefer</c>
	/// labeled alternative in <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateDefer([NotNull] PParser.StateDeferContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>SafetyTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSafetyTestDecl([NotNull] PParser.SafetyTestDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SafetyTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSafetyTestDecl([NotNull] PParser.SafetyTestDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>RefinementTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefinementTestDecl([NotNull] PParser.RefinementTestDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RefinementTestDecl</c>
	/// labeled alternative in <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefinementTestDecl([NotNull] PParser.RefinementTestDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ProveUsingCmd</c>
	/// labeled alternative in <see cref="PParser.proofItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProveUsingCmd([NotNull] PParser.ProveUsingCmdContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ProveUsingCmd</c>
	/// labeled alternative in <see cref="PParser.proofItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProveUsingCmd([NotNull] PParser.ProveUsingCmdContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ProofBlock</c>
	/// labeled alternative in <see cref="PParser.proofBlockDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProofBlock([NotNull] PParser.ProofBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ProofBlock</c>
	/// labeled alternative in <see cref="PParser.proofBlockDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProofBlock([NotNull] PParser.ProofBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>MachineReceive</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineReceive([NotNull] PParser.MachineReceiveContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MachineReceive</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineReceive([NotNull] PParser.MachineReceiveContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>MachineSend</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineSend([NotNull] PParser.MachineSendContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MachineSend</c>
	/// labeled alternative in <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineSend([NotNull] PParser.MachineSendContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ForeignFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeignFunDecl([NotNull] PParser.ForeignFunDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForeignFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeignFunDecl([NotNull] PParser.ForeignFunDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>PFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPFunDecl([NotNull] PParser.PFunDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PFunDecl</c>
	/// labeled alternative in <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPFunDecl([NotNull] PParser.PFunDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>RemoveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemoveStmt([NotNull] PParser.RemoveStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RemoveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemoveStmt([NotNull] PParser.RemoveStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ReceiveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReceiveStmt([NotNull] PParser.ReceiveStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReceiveStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReceiveStmt([NotNull] PParser.ReceiveStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStmt([NotNull] PParser.PrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStmt([NotNull] PParser.PrintStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>SendStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSendStmt([NotNull] PParser.SendStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SendStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSendStmt([NotNull] PParser.SendStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>CompoundStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStmt([NotNull] PParser.CompoundStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CompoundStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStmt([NotNull] PParser.CompoundStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>CtorStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtorStmt([NotNull] PParser.CtorStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CtorStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtorStmt([NotNull] PParser.CtorStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>AssignStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStmt([NotNull] PParser.AssignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStmt([NotNull] PParser.AssignStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>InsertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsertStmt([NotNull] PParser.InsertStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InsertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsertStmt([NotNull] PParser.InsertStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>AnnounceStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnounceStmt([NotNull] PParser.AnnounceStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AnnounceStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnounceStmt([NotNull] PParser.AnnounceStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>AddStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddStmt([NotNull] PParser.AddStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddStmt([NotNull] PParser.AddStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>RaiseStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaiseStmt([NotNull] PParser.RaiseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RaiseStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaiseStmt([NotNull] PParser.RaiseStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ForeachStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachStmt([NotNull] PParser.ForeachStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForeachStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachStmt([NotNull] PParser.ForeachStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>AssumeStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssumeStmt([NotNull] PParser.AssumeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssumeStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssumeStmt([NotNull] PParser.AssumeStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStmt([NotNull] PParser.ContinueStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStmt([NotNull] PParser.ContinueStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] PParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] PParser.IfStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>FunCallStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunCallStmt([NotNull] PParser.FunCallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunCallStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunCallStmt([NotNull] PParser.FunCallStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoStmt([NotNull] PParser.NoStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoStmt([NotNull] PParser.NoStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStmt([NotNull] PParser.WhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStmt([NotNull] PParser.WhileStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStmt([NotNull] PParser.BreakStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStmt([NotNull] PParser.BreakStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>GotoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStmt([NotNull] PParser.GotoStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GotoStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStmt([NotNull] PParser.GotoStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>AssertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertStmt([NotNull] PParser.AssertStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssertStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertStmt([NotNull] PParser.AssertStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] PParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] PParser.ReturnStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>StringExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringExpr([NotNull] PParser.StringExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StringExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringExpr([NotNull] PParser.StringExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>SentExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentExpr([NotNull] PParser.SentExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SentExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentExpr([NotNull] PParser.SentExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>KeywordExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeywordExpr([NotNull] PParser.KeywordExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>KeywordExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeywordExpr([NotNull] PParser.KeywordExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>SeqAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeqAccessExpr([NotNull] PParser.SeqAccessExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SeqAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeqAccessExpr([NotNull] PParser.SeqAccessExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ChooseExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChooseExpr([NotNull] PParser.ChooseExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ChooseExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChooseExpr([NotNull] PParser.ChooseExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedTupleAccessExpr([NotNull] PParser.NamedTupleAccessExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedTupleAccessExpr([NotNull] PParser.NamedTupleAccessExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveExpr([NotNull] PParser.PrimitiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveExpr([NotNull] PParser.PrimitiveExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>BinExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinExpr([NotNull] PParser.BinExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinExpr([NotNull] PParser.BinExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] PParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] PParser.UnaryExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>TupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleAccessExpr([NotNull] PParser.TupleAccessExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleAccessExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleAccessExpr([NotNull] PParser.TupleAccessExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>FlyingExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlyingExpr([NotNull] PParser.FlyingExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FlyingExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlyingExpr([NotNull] PParser.FlyingExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>UnnamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnnamedTupleExpr([NotNull] PParser.UnnamedTupleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnnamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnnamedTupleExpr([NotNull] PParser.UnnamedTupleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>FunCallExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunCallExpr([NotNull] PParser.FunCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunCallExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunCallExpr([NotNull] PParser.FunCallExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpr([NotNull] PParser.CastExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpr([NotNull] PParser.CastExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>TargetsExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTargetsExpr([NotNull] PParser.TargetsExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TargetsExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTargetsExpr([NotNull] PParser.TargetsExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>CtorExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtorExpr([NotNull] PParser.CtorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CtorExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtorExpr([NotNull] PParser.CtorExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] PParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] PParser.ParenExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>QuantExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantExpr([NotNull] PParser.QuantExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>QuantExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantExpr([NotNull] PParser.QuantExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedTupleExpr([NotNull] PParser.NamedTupleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedTupleExpr([NotNull] PParser.NamedTupleExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>TestExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestExpr([NotNull] PParser.TestExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TestExpr</c>
	/// labeled alternative in <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestExpr([NotNull] PParser.TestExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ForeignTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeignTypeDef([NotNull] PParser.ForeignTypeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForeignTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeignTypeDef([NotNull] PParser.ForeignTypeDefContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>PTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPTypeDef([NotNull] PParser.PTypeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PTypeDef</c>
	/// labeled alternative in <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPTypeDef([NotNull] PParser.PTypeDefContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>TupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleLvalue([NotNull] PParser.TupleLvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleLvalue([NotNull] PParser.TupleLvalueContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>NamedTupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedTupleLvalue([NotNull] PParser.NamedTupleLvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedTupleLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedTupleLvalue([NotNull] PParser.NamedTupleLvalueContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>MapOrSeqLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapOrSeqLvalue([NotNull] PParser.MapOrSeqLvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MapOrSeqLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapOrSeqLvalue([NotNull] PParser.MapOrSeqLvalueContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>VarLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarLvalue([NotNull] PParser.VarLvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarLvalue</c>
	/// labeled alternative in <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarLvalue([NotNull] PParser.VarLvalueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] PParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] PParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.iden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIden([NotNull] PParser.IdenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.iden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIden([NotNull] PParser.IdenContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] PParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] PParser.IntContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] PParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] PParser.TypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.idenTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdenTypeList([NotNull] PParser.IdenTypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.idenTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdenTypeList([NotNull] PParser.IdenTypeListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.idenType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdenType([NotNull] PParser.IdenTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.idenType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdenType([NotNull] PParser.IdenTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.funParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunParamList([NotNull] PParser.FunParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.funParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunParamList([NotNull] PParser.FunParamListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.funParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunParam([NotNull] PParser.FunParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.funParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunParam([NotNull] PParser.FunParamContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.topDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopDecl([NotNull] PParser.TopDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.topDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopDecl([NotNull] PParser.TopDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.invariantGroupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvariantGroupDecl([NotNull] PParser.InvariantGroupDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.invariantGroupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvariantGroupDecl([NotNull] PParser.InvariantGroupDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.proofBlockDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProofBlockDecl([NotNull] PParser.ProofBlockDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.proofBlockDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProofBlockDecl([NotNull] PParser.ProofBlockDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.proofBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProofBody([NotNull] PParser.ProofBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.proofBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProofBody([NotNull] PParser.ProofBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.proofItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProofItem([NotNull] PParser.ProofItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.proofItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProofItem([NotNull] PParser.ProofItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.globalParamDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalParamDecl([NotNull] PParser.GlobalParamDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.globalParamDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalParamDecl([NotNull] PParser.GlobalParamDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDefDecl([NotNull] PParser.TypeDefDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.typeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDefDecl([NotNull] PParser.TypeDefDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.enumTypeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumTypeDefDecl([NotNull] PParser.EnumTypeDefDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.enumTypeDefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumTypeDefDecl([NotNull] PParser.EnumTypeDefDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.enumElemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumElemList([NotNull] PParser.EnumElemListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.enumElemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumElemList([NotNull] PParser.EnumElemListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.enumElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumElem([NotNull] PParser.EnumElemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.enumElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumElem([NotNull] PParser.EnumElemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.numberedEnumElemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberedEnumElemList([NotNull] PParser.NumberedEnumElemListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.numberedEnumElemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberedEnumElemList([NotNull] PParser.NumberedEnumElemListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.numberedEnumElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberedEnumElem([NotNull] PParser.NumberedEnumElemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.numberedEnumElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberedEnumElem([NotNull] PParser.NumberedEnumElemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventDecl([NotNull] PParser.EventDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventDecl([NotNull] PParser.EventDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventSetDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventSetDecl([NotNull] PParser.EventSetDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventSetDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventSetDecl([NotNull] PParser.EventSetDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventSetLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventSetLiteral([NotNull] PParser.EventSetLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventSetLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventSetLiteral([NotNull] PParser.EventSetLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceDecl([NotNull] PParser.InterfaceDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceDecl([NotNull] PParser.InterfaceDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.implMachineDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplMachineDecl([NotNull] PParser.ImplMachineDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.implMachineDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplMachineDecl([NotNull] PParser.ImplMachineDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.idenList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdenList([NotNull] PParser.IdenListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.idenList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdenList([NotNull] PParser.IdenListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReceivesSends([NotNull] PParser.ReceivesSendsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.receivesSends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReceivesSends([NotNull] PParser.ReceivesSendsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.specMachineDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecMachineDecl([NotNull] PParser.SpecMachineDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.specMachineDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecMachineDecl([NotNull] PParser.SpecMachineDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.machineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineBody([NotNull] PParser.MachineBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.machineBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineBody([NotNull] PParser.MachineBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.machineEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachineEntry([NotNull] PParser.MachineEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.machineEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachineEntry([NotNull] PParser.MachineEntryContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] PParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] PParser.VarDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunDecl([NotNull] PParser.FunDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.funDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunDecl([NotNull] PParser.FunDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.pureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPureDecl([NotNull] PParser.PureDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.pureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPureDecl([NotNull] PParser.PureDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.invariantDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvariantDecl([NotNull] PParser.InvariantDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.invariantDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvariantDecl([NotNull] PParser.InvariantDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.axiomDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxiomDecl([NotNull] PParser.AxiomDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.axiomDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxiomDecl([NotNull] PParser.AxiomDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.assumeOnStartDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssumeOnStartDecl([NotNull] PParser.AssumeOnStartDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.assumeOnStartDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssumeOnStartDecl([NotNull] PParser.AssumeOnStartDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.stateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateDecl([NotNull] PParser.StateDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.stateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateDecl([NotNull] PParser.StateDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateBodyItem([NotNull] PParser.StateBodyItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.stateBodyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateBodyItem([NotNull] PParser.StateBodyItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.nonDefaultEventList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonDefaultEventList([NotNull] PParser.NonDefaultEventListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.nonDefaultEventList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonDefaultEventList([NotNull] PParser.NonDefaultEventListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.nonDefaultEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonDefaultEvent([NotNull] PParser.NonDefaultEventContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.nonDefaultEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonDefaultEvent([NotNull] PParser.NonDefaultEventContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventList([NotNull] PParser.EventListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventList([NotNull] PParser.EventListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.eventId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventId([NotNull] PParser.EventIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.eventId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventId([NotNull] PParser.EventIdContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateName([NotNull] PParser.StateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateName([NotNull] PParser.StateNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] PParser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] PParser.FunctionBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] PParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] PParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLvalue([NotNull] PParser.LvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLvalue([NotNull] PParser.LvalueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.recvCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecvCase([NotNull] PParser.RecvCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.recvCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecvCase([NotNull] PParser.RecvCaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.anonEventHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnonEventHandler([NotNull] PParser.AnonEventHandlerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.anonEventHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnonEventHandler([NotNull] PParser.AnonEventHandlerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.noParamAnonEventHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoParamAnonEventHandler([NotNull] PParser.NoParamAnonEventHandlerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.noParamAnonEventHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoParamAnonEventHandler([NotNull] PParser.NoParamAnonEventHandlerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] PParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] PParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.formatedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatedString([NotNull] PParser.FormatedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.formatedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatedString([NotNull] PParser.FormatedStringContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.primitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive([NotNull] PParser.PrimitiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.primitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive([NotNull] PParser.PrimitiveContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatLiteral([NotNull] PParser.FloatLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatLiteral([NotNull] PParser.FloatLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.unnamedTupleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnnamedTupleBody([NotNull] PParser.UnnamedTupleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.unnamedTupleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnnamedTupleBody([NotNull] PParser.UnnamedTupleBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.namedTupleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedTupleBody([NotNull] PParser.NamedTupleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.namedTupleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedTupleBody([NotNull] PParser.NamedTupleBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.rvalueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRvalueList([NotNull] PParser.RvalueListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.rvalueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRvalueList([NotNull] PParser.RvalueListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRvalue([NotNull] PParser.RvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRvalue([NotNull] PParser.RvalueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModExpr([NotNull] PParser.ModExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.modExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModExpr([NotNull] PParser.ModExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.bindExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBindExpr([NotNull] PParser.BindExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.bindExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBindExpr([NotNull] PParser.BindExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.namedModuleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedModuleDecl([NotNull] PParser.NamedModuleDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.namedModuleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedModuleDecl([NotNull] PParser.NamedModuleDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.seqPrimitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeqPrimitive([NotNull] PParser.SeqPrimitiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.seqPrimitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeqPrimitive([NotNull] PParser.SeqPrimitiveContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.seqLiteralBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeqLiteralBody([NotNull] PParser.SeqLiteralBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.seqLiteralBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeqLiteralBody([NotNull] PParser.SeqLiteralBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.seqLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeqLiteral([NotNull] PParser.SeqLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.seqLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeqLiteral([NotNull] PParser.SeqLiteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.paramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamBody([NotNull] PParser.ParamBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.paramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamBody([NotNull] PParser.ParamBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] PParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] PParser.ParamContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.twise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTwise([NotNull] PParser.TwiseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.twise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTwise([NotNull] PParser.TwiseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestDecl([NotNull] PParser.TestDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.testDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestDecl([NotNull] PParser.TestDeclContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PParser.implementationDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementationDecl([NotNull] PParser.ImplementationDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PParser.implementationDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementationDecl([NotNull] PParser.ImplementationDeclContext context);
}
} // namespace Plang.Compiler
